# Generated by Django 3.1.3 on 2021-11-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=150)),
                ('data_de_inicio', models.CharField(max_length=10)),
                ('data_de_fim', models.CharField(max_length=10)),
                ('valor_projeto', models.FloatField()),
                ('risco', models.IntegerField(choices=[(0, 'Baixo'), (1, 'Medio'), (2, 'Alto')], default=0)),
                ('participantes', models.CharField(max_length=150)),
            ],
        ),
    ]
